# **Day - 2 : Creating and Manipulating Arrays**

*1.* 

*Write code to import NumPy into your script. Check the version of NumPy installed.*

In [6]:
import numpy as np 
np.__version__

'1.26.4'


*2.* 

*Here is a list below:* 

*list1 = [2, 3, 4, 6]* 

*Create a one-dimensional array from the list above.* 

*Write another  line  of  code  to  check  the  shape  and  size  of  your array.* 

*Write  a  function  that  takes  this  array  and  returns  a  new array with all the values in the original array reversed.*

In [16]:
lst= [2,3,4,6]
arr1= np.array(lst)

In [13]:
arr1.shape

(4,)

In [14]:
arr1.size

4

In [15]:
def newarr(arr):
    return arr[::-1]

newarr(arr1)

array([6, 4, 3, 2])

*3.* 

*list1 = [2, 3, 4, 6]* 

*list2 = [8, 10, 12, 14]* 

*Create an array from the two lists above.* 

*Then write code to check the shape, dimensions,  and data type of the array.*

In [17]:
list1 = [2, 3, 4, 6]
list2 = [8, 10, 12, 14]

In [20]:
arr2=np.array([list1, list2])
arr2

array([[ 2,  3,  4,  6],
       [ 8, 10, 12, 14]])

In [21]:
arr2.shape

(2, 4)

In [22]:
arr2.ndim

2

In [23]:
arr2.dtype

dtype('int32')

*4.* 

*list1 = [2, 3, 4, 6]* 

*list2 = [8, 10.1, 12, 14]* 

*list3 = [16, 18, 20, 22.1]* 

*Create  an  array  from  the  three  (3)  lists  above.*

*Take  note that  some  of  the  lists  contain  floats.  Create  an  array  that will have an int64 data type.*

In [24]:
list1 = [2, 3, 4, 6] 
list2 = [8, 10.1, 12, 14] 
list3 = [16, 18, 20, 22.1] 

In [26]:
arr3= np.array([list1, list2, list3])
arr3

array([[ 2. ,  3. ,  4. ,  6. ],
       [ 8. , 10.1, 12. , 14. ],
       [16. , 18. , 20. , 22.1]])

In [27]:
arr3.dtype

dtype('float64')

In [29]:
arr4= np.array([list1, list2, list3], dtype='int64')

In [30]:
arr4

array([[ 2,  3,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]], dtype=int64)

*5.* 

*Is it possible to create an array of both floats and integers?*

In [31]:
# yessss
list5 = [1,2,3,4,5,6,7.7,9]
combined_arr=np.array(list5)

In [32]:
combined_arr.dtype

dtype('float64')