# **Day - 8 : Slicing NumPy Arrays**

*1.*

*Create a one-dimensional array with random integers between 0 and 20. The size of the array is 10. Ensure that the results are reproducible.* 

In [12]:
import numpy as np

rng = np.random.default_rng(seed=42)
array1 = rng.integers(21, size=10)
array1

array([ 1, 16, 13,  9,  9, 18,  1, 14,  4,  1], dtype=int64)

*2.*

*Using slicing, create a subset array of 3 integers from the array you created in question 1. The first integer is at index 2, the second integer is at index 4, and the third index i at index 7.* 

In [3]:
subset_array = array1[[2, 4, 7]]
print(subset_array)

[13  9 14]


*3.*

*Create a two-dimensional array from the list below. Check the dimensions and shape of your array.* 

*Using slicing, write a code to access the numbers 3, 8, and 13. Your code should return [3, 8, 13].*

In [5]:
my_list = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]]

array2 = np.array(my_list)
array2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [6]:
array2.ndim

2

In [7]:
array2.shape

(3, 5)

In [8]:
sub_array = array2[0, 2], array2[1, 2], array2[2,2]
print(np.array(sub_array))

[ 3  8 13]


In [10]:
my_list = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]]

array2 = np.array(my_list)

sub_array = array2[0, 2], array2[1, 2], array2[2,2]
print(np.array(sub_array))


[ 3  8 13]


# **Day - 4 : NumPy Arrays and Vector Operations**

*4.*

*Using  slicing,  write  code  that  creates  a  sublist  from  the array  you  created.  Your  code  should  return  an  array  of numbers (4, 8, and 15).*

In [11]:
my_list = [[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]]]

array3 = np.array(my_list)

sub_list = array3[0,0,3], array3[0,1,2], array3[0,2,4]
np.array(sub_list)

array([ 4,  8, 15])